### ISSUE TITLE
Problem with installing the plugin

### ISSUE THREAD

**Issue by introvert** [ivinteractive/kirbycms-redirects#10]
Hey,

When I install the plugin in the site/plugins/redirecty I get the following error when I want to access the admin panel:

`Whoops \ Exception \ ErrorException (E_ERROR)
Method Kirby\Panel\View::__toString() must not throw an exception, caught Error: Call to a member function redirects() on boolean`

Any idea how should I fix this?

Thanks

**Comment by ivi-admin** [comment]
Hey @introvert, that should be fixed now with [this commit](https://github.com/ivinteractive/kirbycms-redirects/commit/1dbeb9d97528e90d9fc4e04bf0095c2ccb98bb94). The issue was that in the widget (and also in the redirecty() function), it wasn't doing a check for the redirects page's existence before trying to pull the redirects from it. You can update to the latest version, or just create the redirects content page directory/file via the CLI.
